const SYSTEM_PROMPT = `You are a Socratic Journaling Companion. Your sole purpose is to help the user clarify their thoughts, uncover hidden assumptions, and work through complex problems.
Strict Rules:
1. Never offer solutions, advice, or summaries. Do not tell them what to do.
2. Be incredibly brief (maximum 2-3 sentences).
3. End every response with exactly ONE clear, deep, open-ended question. Never ask multiple questions.
4. Actively listen for logical gaps, cognitive distortions, or unstated assumptions, and gently ask a question about that specific pivot point.
5. Tone: Grounded, empathetic, non-judgmental, and intellectually curious.`;
const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const MODEL = "llama-3.3-70b-versatile";
const corsHeaders = (origin, allowedOrigin) => ({ "Access-Control-Allow-Origin": origin === allowedOrigin ? origin : allowedOrigin, "Access-Control-Allow-Methods":"POST, OPTIONS", "Access-Control-Allow-Headers":"Content-Type", "Vary":"Origin" });
const json = (body,status,headers) => new Response(JSON.stringify(body),{status,headers:{...headers,"Content-Type":"application/json"}});
export default { async fetch(request,env) { const origin=request.headers.get("Origin")||""; const headers=corsHeaders(origin,env.ALLOWED_ORIGIN); if(request.method==="OPTIONS")return new Response(null,{headers});if(request.method!=="POST"||new URL(request.url).pathname!=="/chat")return json({error:"Not found."},404,headers);if(origin!==env.ALLOWED_ORIGIN)return json({error:"This origin is not permitted."},403,headers);try {const body=await request.json(),messages=body?.messages;if(!Array.isArray(messages)||messages.length<1||messages.length>40)return json({error:"Invalid conversation."},400,headers);if(!messages.every(message=>message&&["user","assistant"].includes(message.role)&&typeof message.content==="string"&&message.content.length<=6000))return json({error:"Invalid message content."},400,headers);const groqResponse=await fetch(GROQ_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${env.GROQ_API_KEY}`},body:JSON.stringify({model:MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},...messages],temperature:.7,max_tokens:180})});const data=await groqResponse.json();if(!groqResponse.ok)return json({error:data?.error?.message||"The AI service could not respond."},groqResponse.status,headers);const message=data?.choices?.[0]?.message?.content?.trim();if(!message)return json({error:"No reflection was returned."},502,headers);return json({message},200,headers)}catch{return json({error:"The request could not be processed."},500,headers)}} };
